### ISSUE TITLE
Please add resource_group parameter (already available in CreateImage API)

### ISSUE THREAD

**Issue by nikita-golovin** [hashicorp/packer-plugin-alicloud#59]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Please add capability to specify **resource group** for images. This parameter is supported by [CreateImage](https://api.aliyun.com/#/?product=Ecs&version=2014-05-26&api=CreateImage) API but not used by AliCloud builder

#### Use Case(s)

Taxonomy of resources (e.g. for billing)

**Comment by nywilken** [comment]
Hi @nikita-golovin thanks for reaching out here. This is a community maintained plugin so the Packer team won't work on this change. But we are happy to review a pull-request if you are or a member of the community is interested in making the change.
